# Clarinet Project Configuration

[project]
name = "stackscope"
clarity_version = 2
cache_dir = ".clarinet/cache"

[contracts.stackscope-notes]
path = "contracts/stackscope-notes.clar"
clarity_version = 2

# Testnet configuration
[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "${STX_WALLET_MNEMONIC}"
balance = 100_000_000_000
derivation = "m/44'/5757'/0'/0/0"
