[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "${STX_WALLET_MNEMONIC}"
balance = 100_000_000_000
derivation = "m/44'/5757'/0'/0/0"
